estagioRota/conversor/urls.py
from django.urls import path

from . import views

app_name = 'conversor'

urlpatterns = [path('', views.index, name='index'), 
               path('resultado', views.resultado, name='resultado'),
               ]

estagioRota/divide/urls.py
from django.urls import path

from . import views

app_name = 'divide'


urlpatterns = [path('', views.index, name='index'), 
               path('cadastro', views.cadastro, name='cadastro'),
               path('resultado', views.resultado, name='resultado'),
               ]

estagioRota/estagioRota/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
    path('conversor/', include('conversor.urls')),
    path('jogodavida/', include('jogoVida.urls')),
    path('divide/', include('divide.urls')),
]

estagioRota/inicio/urls.py
from django.urls import path

from . import views

app_name = 'inicio'


urlpatterns = [path('', views.index, name='index'), 
               ]

estagioRota/jogoVida/urls.py
from django.urls import path, register_converter

from . import views

app_name = 'jogoVida'

class ListConverter:
    regex = '.*\/*'

    def to_python(self, list):
        return list

    def to_url(self, list):
        return list

register_converter(ListConverter, 'list')

urlpatterns = [path('', views.index, name='index'), 
               path('novo', views.novo, name='novo'),
               path('<list:matriz>proximo', views.proximo, name='proximo'),
               ]

estagioRota/divide/models.py
from django.db import models

# Create your models here.
class Produto(models.Model):# definição da classe produto e da tabela produto no banco de dados
    nome = models.CharField(max_length=100)
    preco = models.FloatField()

    def getPreco(self):
        return self.preco
    def __str__(self):
        return '{} ({})'.format(self.nome, self.preco)

estagioRota/inicio/models.py
from django.db import models

# Create your models here.

estagioRota/conversor/views.py
from django.shortcuts import render
from .Conversor import conv

# Create your views here.
def index(request):# retorna a view com o formulário
    return render(request, 'conversor/index.html')

def resultado(request):# retorna para a view inicial com o resultado
    if request.method == "GET":
        n = request.GET.__getitem__('romano')
        resultado = conv(n)
        if type(resultado) == int:
            return render(request, 'conversor/index.html', {'resultado': resultado})
        return render(request, 'conversor/index.html', {'error_message': resultado})
    return render(request, 'conversor/index.html')
    

estagioRota/divide/views.py
from django.shortcuts import render
from .divisor import divide
from .models import Produto

# Create your views here.
def index(request): #retorna a view com o formulário de quantos clientes
    return render(request, 'divide/index.html')

def cadastro(request):#retorna a view com o formulário que possui o número de campos requisitado
    if request.method == "GET":
        quantidade = request.GET.__getitem__('pessoas')
        produtos = Produto.objects.all()
        return render(request, 'divide/form.html', {'quantidade': range(0, int(quantidade)), 'produtos': produtos, 'quant': quantidade})
    
def resultado(request):# retorna a view com o resultado final
     if request.method == "POST":
        resultado = divide(request.POST)
        return render(request, 'divide/resultado.html', {"resultado": resultado})
        
    

estagioRota/inicio/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'inicio/index.html')

estagioRota/jogoVida/views.py
from django.shortcuts import render
from .jogo import novoJogo, rodada
# Create your views here.

def index(request):# view inicial
    return render(request, 'jogoVida/index.html')

def novo(request):# view com um novo tabuleiro gerado aleatóriamente
    matriz = novoJogo()
    return render(request, 'jogoVida/index.html', {'matriz': matriz})

def proximo(request, matriz):# view com a próxima rodada(geração)
    prox = rodada(matriz)
    return render(request, 'jogoVida/index.html', {'matriz': prox})

estagioRota/conversor/templates/conversor/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Conversor de números romanos</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body>
      <!-- menu -->
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'inicio:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'conversor:index' %}">Conversor de números romanos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'jogoVida:index' %}">Jogo da vida</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'divide:index' %}">Divisor de conta de restaurante</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <!-- fim do menu -->
        <div class="container">
          <h1 class="mt-3">Conversor de números romanos</h1>
        </div>
        <br><br>
        <div class="container">
          <form action="{% url 'conversor:resultado' %}" method="get">
              {% csrf_token %}
              <label for="romano" class="form-label">Digite o número romano</label>
              <input type="text" id="romano" name="romano" class="form-control">
              {% if error_message %}<!-- se o número não for válido traz uma mensagem de erro -->
              <p style="color: red;"><strong>{{ error_message }}</strong></p>
              {% endif %}
              <button type="submit" class="btn btn-primary mt-3">Enviar</button>
          </form>
        </div>
        <br><br><br>
        {% if resultado %}<!-- se existir um resultado então ele é mostrado -->
        <div class="container">
            <h2 class="">O número é {{ resultado }}</h2>
        </div>
        {% endif %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>

estagioRota/divide/templates/divide/form.html
<!DOCTYPE html>
<html>
    <head>
        <title>Divisor de conta</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <style>
            select{
                margin-bottom: 5px;
                margin-left: 5px;
            }
        </style>
    </head>
    <body>
      <!-- menu -->
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'inicio:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'conversor:index' %}">Conversor de números romanos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'jogoVida:index' %}">Jogo da vida</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'divide:index' %}">Divisor de conta de restaurante</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <!-- fim do menu -->
        <div class="container mb-3 mt-3">
        <h1>Divisor de conta</h1>
        </div>
        <div class="container col-6">
        <form action="{% url 'divide:resultado' %}" method="post">
            {% csrf_token %}
            {% for i in quantidade %}<!-- irá construir uma quantidade de campos conforme foi pedido no formulário anterior -->
            <label class="form-label" for="nome{{i}}">Cliente: </label>
            <input class="form-control mb-3" type="text" id="nome{{i}}" name="nome{{i}}">
            <input class="form-check-input" type="checkbox" id="servico{{i}}" name="servico{{i}}">
            <label class="form-check-label mb-3" for="servico{{i}}">Irá pagar a taxa de serviço?</label>
            <br>
            <label class="form-label" for="C{{i}}P0">selecione o produto consumido:</label>
            <div id="C{{i}}">
            <select class="form-select" name="C{{i}}P0">
                <option value="-1" selected>Nada</option>
                {% for prod in produtos %}<!-- constrói dinamicamente as opções do select de acordo com os produtos especificados no banco de dados -->
                <option value="{{prod.id}}">{{prod}}</option>
                {% endfor %}
            </select>
            </div>
            <br>
            <button class="add-prod btn btn-primary" type="button" id="{{i}}">Adicionar outro produto</button><!-- adiciona outro select para preencher -->
            <hr class="border border-dark border-3 opacity-75">
            <br>
            {% endfor %}
            <input type="hidden" value="{{quant}}" name="quant" id="quant"><!-- campo escondido apenas para passar o numero de clientes já que a quantidade é um range() e não um int -->
            <button class="btn btn-primary mb-5 col-3" type="submit">Enviar</button>
        </form>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        {% load static %}
        <script src="{% static 'jquery/jquery-3.7.0.min.js' %}"></script>
        <script>
            $(document).ready(function(){//função jQuery para adicionar novos campos de produtos
                $(".add-prod").click(function(){
                    var id = this.id;
                    var $select = $(`select[name^='C${id}']:last`).clone(true, true);
                    var num = parseInt( $select.prop("name").match(/\d+$/g), 10) +1;
                    var $prod = $select.clone().prop('name', `C${id}P`+num);
                    $(`div[id^='C${id}']`).append($prod);

                });
            });
        </script>
    </body>
</html>

estagioRota/divide/templates/divide/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Divisor de conta</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body>
      <!-- menu -->
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'inicio:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'conversor:index' %}">Conversor de números romanos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'jogoVida:index' %}">Jogo da vida</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'divide:index' %}">Divisor de conta de restaurante</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <!-- fim do menu -->
        <div class="container-fluid mt-3 mb-3">
          <h1>Divisor de conta</h1>
        </div>
        <form action="{% url 'divide:cadastro' %}" method="get">
            {% csrf_token %}
            <div class="container col-3">
              <label class="form-label" for="pessoas">Digite o número de pessoas</label>
              <input class="form-control mb-3" type="number" id="pessoas" name="pessoas">
              <button class="btn btn-primary" type="submit">Enviar</button>
            </div>
        </form>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>

estagioRota/divide/templates/divide/resultado.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Resultados</title>
</head>
<body>
    {% for item in resultado %}
    <p>{{item}}</p>
    {% endfor %}
</body>
</html>

estagioRota/inicio/templates/inicio/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Página inicial</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'conversor:index' %}">Conversor de números romanos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'jogoVida:index' %}">Jogo da vida</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'divide:index' %}">Divisor de conta de restaurante</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container-fluid mt-3">
        <h1>Olá, escolha uma das opções do menu acima</h1>
      </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

estagioRota/jogoVida/templates/jogoVida/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Jogo da vida</title>
        <meta lang="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body>
      <!-- menu -->
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'inicio:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'conversor:index' %}">Conversor de números romanos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'jogoVida:index' %}">Jogo da vida</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'divide:index' %}">Divisor de conta de restaurante</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <!-- fim do menu -->
        <div class="container mb-3 mt-3">
          <h1>Jogo da vida</h1>
        </div>
        <!-- se existir um tabuleiro criado será construído a legenda e o tabuleiro -->
        {% if matriz %}
        <div class="container col-2 mb-3">
        <div style="float: left; display: inline; height: 20px; border: 1px solid black; width: 20px; background-color: green;"></div> <div style="display: inline; margin-left: 5px;"> = célula com vida</div>
        <br>
        <div style="float: left; display: inline; height: 20px; border: 1px solid black; width: 20px;"></div> <div style="display: inline; margin-left: 5px;"> = célula sem vida</div>
        </div>
        <div class="container col-2 mb-3">
        <table class="table table-bordered table-sm">
            {% for i in matriz %}
                <tr style="border: 1px solid black;">
                {% for j in i %}
                {% if j == 1 %}
                    <td style="background-color: green; border: 1px solid black; width: 30px; height: 30px;"></td>
                {% else %}
                    <td style="border: 1px solid black; width: 30px; height: 30px;"></td>
                {% endif %}
                {% endfor %}
                </tr>
            {% endfor %}
        </table>
        </div>
        {% endif %}
        <!-- botões para gerar um novo tabuleiro ou para avançar uma geração no atual -->
      <div class="container col-2">
        <div class="row">
          <div class="col col-6">
          <button class="btn btn-primary" onclick="location.href='{% url 'jogoVida:novo' %}'">Gerar novo</button>
          </div>
          <div class="col col-6">
          <button class="btn btn-primary" onclick="location.href='{% url 'jogoVida:proximo' matriz %}'">Próxima geração</button>
          </div>
        </div>
      </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>